### ISSUE TITLE
Final IT Expo Abstract

### ISSUE THREAD

**Issue by Nicholas-Lawson** [sukhbirsekhon/Hobbyistic#47]
On Canvas, there is an assignment for the Final IT Expo Abstract:

Submit your Abstract. Each team is required to prepare an IT Expo Abstract that will be published in conference material for your project. Make sure you are submitting an abstract that you will want to be published to the public for the IT Expo. Limit your abstract to a maximum of 150 words (any more than 150 will be rejected).

**Comment by classaccounts** [comment]
It was accepted by the grader.
